# Generated by Django 2.2.1 on 2019-06-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageStorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
