# Generated by Django 2.2.1 on 2019-06-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('article', '0005_auto_20190626_1447'),
        ('course', '0001_initial'),
        ('storage', '0003_auto_20190617_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('VO_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('TO_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='News_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('NO_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.News')),
            ],
        ),
        migrations.CreateModel(
            name='Insti_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('IO_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('CO_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base')),
            ],
        ),
    ]
