# Generated by Django 2.2.2 on 2019-06-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190626_1816'),
        ('User', '0001_initial'),
        ('storage', '0003_auto_20190617_1555'),
        ('article', '0005_auto_20190626_1447'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstiOrder',
            new_name='Course_Order',
        ),
        migrations.RenameModel(
            old_name='NewsOrder',
            new_name='Insti_Order',
        ),
        migrations.RenameModel(
            old_name='CourseOrder',
            new_name='News_Order',
        ),
        migrations.RenameModel(
            old_name='TeacherOrder',
            new_name='Teacher_Order',
        ),
        migrations.RenameModel(
            old_name='VideoOrder',
            new_name='Video_Order',
        ),
        migrations.RemoveField(
            model_name='course_order',
            name='IO_id',
        ),
        migrations.RemoveField(
            model_name='insti_order',
            name='NO_id',
        ),
        migrations.RemoveField(
            model_name='news_order',
            name='CO_id',
        ),
        migrations.AddField(
            model_name='course_order',
            name='CO_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insti_order',
            name='IO_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.Institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_order',
            name='NO_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.News'),
            preserve_default=False,
        ),
    ]
