# Generated by Django 2.2.1 on 2019-06-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_auto_20190617_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Base',
            fields=[
                ('course_base_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程ID')),
                ('course_location_province', models.CharField(max_length=10, verbose_name='所在省份')),
                ('course_location_city', models.CharField(max_length=20, verbose_name='所在城市')),
                ('course_location_area', models.CharField(max_length=20, verbose_name='所在区')),
                ('course_location', models.CharField(default='UNKOWN LOCATION', max_length=20, verbose_name='上课地点')),
                ('course_price', models.IntegerField(default=0, max_length=10, verbose_name='单次课价格')),
                ('course_subject', models.CharField(max_length=10, verbose_name='课程方向')),
                ('course_contains', models.CharField(blank=True, max_length=500, verbose_name='课程内容')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_Teacher', to='User.Teach', verbose_name='授课老师')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='该次课程ID')),
                ('course_start_time', models.DateTimeField(verbose_name='首次课时间')),
                ('course_duration_of_week', models.IntegerField(choices=[(4, '一月'), (12, '一季'), (26, '半年'), (52, '一年'), (104, '两年')])),
                ('course_homework', models.TextField(max_length=500, verbose_name='课程作业')),
                ('course_base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base', verbose_name='大课程ID')),
            ],
        ),
    ]
