# Generated by Django 2.2.1 on 2019-06-26 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_location_province', models.CharField(max_length=10, verbose_name='所在省份')),
                ('course_location_city', models.CharField(max_length=20, verbose_name='所在城市')),
                ('course_location_area', models.CharField(max_length=20, verbose_name='所在区')),
                ('course_teacher', models.CharField(max_length=30, verbose_name='授课老师')),
                ('course_subject', models.CharField(choices=[('All', 'All'), ('Chin', 'Chinese'), ('Math', 'Mathematics'), ('Eng', 'English'), ('Phy', 'Physics'), ('Chem', 'Chemistry'), ('Bio', 'Biology'), ('His', 'History'), ('Geo', 'Geography'), ('Poli', 'Politics')], max_length=10, verbose_name='课程方向')),
                ('course_age', models.CharField(choices=[('All', 'All'), ('Pri', 'Primary'), ('Jun', 'Junior'), ('Sen', 'Senior')], max_length=10, verbose_name='课程适用年龄')),
                ('course_contains', models.CharField(blank=True, max_length=500, verbose_name='课程内容')),
                ('course_time', models.DateTimeField(verbose_name='首次课时间')),
                ('course_duration_of_week', models.IntegerField(choices=[(12, '一季'), (26, '半年'), (52, '一年'), (104, '两年')])),
                ('course_price', models.IntegerField(default=0, verbose_name='课程价格')),
            ],
            options={
                'db_table': 'Course_Base',
            },
        ),
        migrations.CreateModel(
            name='Course_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Course_by_Teacher', to='course.Course_Base', verbose_name='教师所授课程')),
                ('course_teacher', models.ManyToManyField(related_name='Teacher_for_course', to='User.Teacher', verbose_name='教师名称')),
            ],
            options={
                'db_table': 'Course_Teacher',
            },
        ),
        migrations.CreateModel(
            name='Course_Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Course_by_Ins', to='course.Course_Base', verbose_name='机构所授课程')),
                ('course_ins', models.ManyToManyField(related_name='Ins_for_Course', to='User.Institution', verbose_name='机构名称')),
            ],
            options={
                'db_table': 'Course_Institution',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_location', models.CharField(default='UNKOWN LOCATION', max_length=20, verbose_name='上课地点')),
                ('course_time', models.DateTimeField(verbose_name='本次课时间')),
                ('course_homework', models.TextField(max_length=500, verbose_name='课程作业')),
                ('course_base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
