# Generated by Django 2.2.1 on 2019-06-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_base',
            name='course_homework',
            field=models.TextField(blank=True, max_length=500, verbose_name='课程作业'),
        ),
        migrations.AddField(
            model_name='course_base',
            name='course_location',
            field=models.CharField(default='UNKOWN LOCATION', max_length=20, verbose_name='上课地点'),
        ),
        migrations.AlterField(
            model_name='course_base',
            name='course_location_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_distinct', to='CHINA_LOCATION.ChinaLocation', verbose_name='所在区'),
        ),
        migrations.AlterField(
            model_name='course_base',
            name='course_location_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_city', to='CHINA_LOCATION.ChinaLocation', verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='course_base',
            name='course_location_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_province', to='CHINA_LOCATION.ChinaLocation', verbose_name='所在省份'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
