# Generated by Django 2.2.2 on 2019-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_base',
            name='course_homework',
            field=models.TextField(default=0, max_length=500, verbose_name='课程作业'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_base',
            name='course_location',
            field=models.CharField(default='UNKOWN LOCATION', max_length=20, verbose_name='上课地点'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
