# Generated by Django 2.2.1 on 2019-06-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_base',
            old_name='course_location_area',
            new_name='course_location_distinct',
        ),
    ]
