# Generated by Django 2.2.1 on 2019-06-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_institution_name'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher', verbose_name='评价者')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base', verbose_name='被评价课程')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
