# Generated by Django 2.2.1 on 2019-06-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_score', models.SmallIntegerField(verbose_name='课程评分')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='course.Course_Base', verbose_name='被评分课程')),
            ],
            options={
                'db_table': 'Course_Score',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
