# Generated by Django 2.2.1 on 2019-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190626_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_base',
            name='course_name',
            field=models.CharField(default=0, max_length=20, verbose_name='课程名称'),
            preserve_default=False,
        ),
    ]
