# Generated by Django 2.2.1 on 2019-06-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_comment',
            name='comment_parent',
            field=models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='User.Teacher', verbose_name='评价者'),
        ),
        migrations.AlterField(
            model_name='course_comment',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base', verbose_name='被评价课程'),
        ),
    ]
