# Generated by Django 2.2.1 on 2019-06-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190626_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_base',
            name='course_age',
            field=models.CharField(choices=[('All', 'All'), ('Primary', 'Pri'), ('Junior', 'Jun'), ('Senior', 'Sen')], max_length=10, verbose_name='课程适用年龄'),
        ),
        migrations.AlterField(
            model_name='course_base',
            name='course_subject',
            field=models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=10, verbose_name='课程方向'),
        ),
    ]
