# Generated by Django 2.2.2 on 2019-06-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_base_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_base',
            name='course_location_area',
            field=models.CharField(max_length=20, verbose_name='所在区'),
        ),
        migrations.AlterField(
            model_name='course_base',
            name='course_location_city',
            field=models.CharField(max_length=20, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='course_base',
            name='course_location_province',
            field=models.CharField(max_length=10, verbose_name='所在省份'),
        ),
        migrations.AlterField(
            model_name='course_base',
            name='course_name',
            field=models.CharField(max_length=50, verbose_name='课程名称'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_location', models.CharField(default='UNKOWN LOCATION', max_length=20, verbose_name='上课地点')),
                ('course_time', models.DateTimeField(verbose_name='本次课时间')),
                ('course_homework', models.TextField(max_length=500, verbose_name='课程作业')),
                ('course_base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
