# Generated by Django 2.2.1 on 2019-06-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190626_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_institution',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_by_Ins', to='course.Course_Base', verbose_name='机构所授课程'),
        ),
        migrations.AlterField(
            model_name='course_institution',
            name='course_ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ins_for_Course', to='User.Branch', verbose_name='机构名称'),
        ),
        migrations.AlterField(
            model_name='course_teacher',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_by_Teacher', to='course.Course_Base', verbose_name='教师所授课程'),
        ),
    ]
