# Generated by Django 2.2.2 on 2019-06-17 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_auto_20190617_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='tlesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.POS', verbose_name='视听用户')),
            ],
        ),
    ]
