# Generated by Django 2.2.2 on 2019-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_lesson',
            name='state',
            field=models.CharField(default='未通过', max_length=8),
        ),
    ]
