# Generated by Django 2.2.1 on 2019-06-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20190627_2206'),
        ('course', '0004_auto_20190627_2206'),
        ('userHome', '0002_auto_20190627_1213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temp_lesson',
            unique_together={('person', 'lesson')},
        ),
    ]
