# Generated by Django 2.2.2 on 2019-06-26 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('Id_num', models.CharField(max_length=18)),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15)),
                ('Limyear', models.IntegerField(default=0)),
                ('Fitage', models.CharField(choices=[('All', 'All'), ('Primary', 'Pri'), ('Junior', 'Jun'), ('Senior', 'Sen')], max_length=15)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Brief', models.CharField(max_length=80)),
                ('Wallet', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tea', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=30)),
                ('KName', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Birthday', models.DateField()),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15)),
                ('FeeRange', models.IntegerField()),
                ('Area', models.CharField(max_length=10)),
                ('Wallet', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='POS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_num', models.CharField(max_length=18)),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15)),
                ('Fitage', models.CharField(choices=[('All', 'All'), ('Primary', 'Pri'), ('Junior', 'Jun'), ('Senior', 'Sen')], max_length=15)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Brief', models.CharField(max_length=80)),
                ('Wallet', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Ins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=64)),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15)),
                ('Fitage', models.CharField(choices=[('All', 'All'), ('Primary', 'Pri'), ('Junior', 'Jun'), ('Senior', 'Sen')], max_length=15)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Adm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
