# Generated by Django 2.2.1 on 2019-06-18 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Tid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('Id_num', models.CharField(max_length=18)),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chin', 'Chinese'), ('Math', 'Mathematics'), ('Eng', 'English'), ('Phy', 'Physics'), ('Chem', 'Chemistry'), ('Bio', 'Biology'), ('His', 'History'), ('Geo', 'Geography'), ('Poli', 'Politics')], max_length=15)),
                ('Limyear', models.IntegerField(default=0)),
                ('Fitage', models.CharField(choices=[('All', 'All'), ('Pri', 'Primary'), ('Jun', 'Junior'), ('Sen', 'Senior')], max_length=15)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Brief', models.CharField(max_length=80)),
                ('Wallet', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tea', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=30)),
                ('KName', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Birthday', models.DateField()),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chin', 'Chinese'), ('Math', 'Mathematics'), ('Eng', 'English'), ('Phy', 'Physics'), ('Chem', 'Chemistry'), ('Bio', 'Biology'), ('His', 'History'), ('Geo', 'Geography'), ('Poli', 'Politics')], max_length=15)),
                ('FeeRange', models.IntegerField()),
                ('Area', models.CharField(max_length=10)),
                ('Wallet', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='POS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('Iid', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_num', models.CharField(max_length=18)),
                ('Address', models.CharField(max_length=64)),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chin', 'Chinese'), ('Math', 'Mathematics'), ('Eng', 'English'), ('Phy', 'Physics'), ('Chem', 'Chemistry'), ('Bio', 'Biology'), ('His', 'History'), ('Geo', 'Geography'), ('Poli', 'Politics')], max_length=15)),
                ('Fitage', models.CharField(choices=[('All', 'All'), ('Pri', 'Primary'), ('Jun', 'Junior'), ('Sen', 'Senior')], max_length=15)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Brief', models.CharField(max_length=80)),
                ('Wallet', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Ins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Aid', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Adm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
