# Generated by Django 2.2.1 on 2019-06-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='Address',
        ),
        migrations.AlterField(
            model_name='institution',
            name='Fitage',
            field=models.CharField(choices=[('All', 'All'), ('Primary', 'Pri'), ('Junior', 'Jun'), ('Senior', 'Sen')], max_length=15),
        ),
        migrations.AlterField(
            model_name='institution',
            name='LDirection',
            field=models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='LDirection',
            field=models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Fitage',
            field=models.CharField(choices=[('All', 'All'), ('Primary', 'Pri'), ('Junior', 'Jun'), ('Senior', 'Sen')], max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='LDirection',
            field=models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=64)),
                ('LDirection', models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], max_length=15)),
                ('Fitage', models.CharField(choices=[('All', 'All'), ('Primary', 'Pri'), ('Junior', 'Jun'), ('Senior', 'Sen')], max_length=15)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Branch', to='User.Institution')),
            ],
        ),
    ]
