# Generated by Django 2.2.2 on 2019-06-17 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(max_length=18, verbose_name='标识码')),
                ('address', models.CharField(max_length=64, verbose_name='店面地址')),
                ('field', models.CharField(max_length=64, verbose_name='教育领域')),
                ('fitage', models.IntegerField(verbose_name='教育适合年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('brief', models.CharField(max_length=40, verbose_name='简介')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('pname', models.CharField(max_length=32, verbose_name='家长姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('id_num', models.CharField(max_length=18, verbose_name='身份证号')),
                ('field', models.CharField(max_length=64, verbose_name='教育领域')),
                ('limyear', models.IntegerField(default=0, verbose_name='从教年限')),
                ('fitage', models.IntegerField(verbose_name='教育适合年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('brief', models.CharField(max_length=40, verbose_name='简介')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminInfo',
        ),
        migrations.DeleteModel(
            name='InstInfo',
        ),
        migrations.DeleteModel(
            name='POSInfo',
        ),
        migrations.DeleteModel(
            name='TeachInfo',
        ),
    ]
