# Generated by Django 2.2.1 on 2019-06-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190626_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Institution'),
        ),
    ]
