# Generated by Django 2.2.2 on 2019-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190627_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='name',
            field=models.CharField(default='待填写', max_length=30),
        ),
    ]
