# Generated by Django 2.2.2 on 2019-06-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_institution_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='Birthday',
        ),
    ]
