# Generated by Django 2.2.2 on 2019-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190627_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Address',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
