# Generated by Django 2.2.2 on 2019-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='name',
            field=models.CharField(default='待填写', max_length=30),
        ),
    ]
