# Generated by Django 2.2.2 on 2019-06-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_parent_birthday'),
        ('User', '0005_institution_name'),
    ]

    operations = [
    ]
