# Generated by Django 2.2.2 on 2019-06-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_merge_20190627_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Area',
            field=models.CharField(default='All', max_length=10),
        ),
        migrations.AlterField(
            model_name='parent',
            name='FeeRange',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='parent',
            name='LDirection',
            field=models.CharField(choices=[('All', 'All'), ('Chinese', 'Chin'), ('Mathematics', 'Math'), ('English', 'Eng'), ('Physics', 'Phy'), ('Chemistry', 'Chem'), ('Biology', 'Bio'), ('History', 'His'), ('Geography', 'Geo'), ('Politics', 'Poli')], default='All', max_length=15),
        ),
    ]
