# Generated by Django 2.2.1 on 2019-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imageFile', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
