# Generated by Django 2.2.1 on 2019-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='IMAGE_ID')),
                ('name', models.CharField(max_length=500, verbose_name='IMAGE_NAME')),
                ('imageFile', models.ImageField(upload_to='images/', verbose_name='IMAGE_URL')),
            ],
        ),
        migrations.DeleteModel(
            name='storage',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='videoFile',
            field=models.FileField(default=0, upload_to='videos/', verbose_name='VIDEO_URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='video_ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=500, verbose_name='VIDEO_NAME'),
        ),
    ]
