# Generated by Django 2.2.2 on 2019-06-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('User', '0002_auto_20190627_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base')),
                ('P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('TPrice', models.FloatField()),
                ('Time', models.DateTimeField()),
                ('P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Parent')),
            ],
        ),
    ]
