# Generated by Django 2.2.1 on 2019-06-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_auto_20190627_2206'),
        ('User', '0007_auto_20190627_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base')),
                ('P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('TPrice', models.FloatField()),
                ('Time', models.DateTimeField()),
                ('C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base')),
                ('P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Parent')),
            ],
        ),
    ]
