# Generated by Django 2.2.2 on 2019-06-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('course', '0004_auto_20190626_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course_Base')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('TPrice', models.FloatField()),
                ('Time', models.DateTimeField()),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Parent')),
            ],
        ),
    ]
