# Generated by Django 2.2.1 on 2019-06-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay_record',
            old_name='Pid',
            new_name='P',
        ),
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='Cid',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='Pid',
            new_name='P',
        ),
    ]
